<?php

use Illuminate\Database\Seeder;

class CurrencySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        if (\DB::table('currencies')->count() > 0) {
            return;
        }

        DB::table('currencies')->insert([
            ['code' => 'AFN', 'name' => 'Afghani', 'symbol' => '؋', 'isDefault' => false,],
            ['code' => 'ALL', 'name' => 'Lek', 'symbol' => 'Lek', 'isDefault' => false,],
            ['code' => 'ANG', 'name' => 'Netherlands Antillian Guilder', 'symbol' => 'ƒ', 'isDefault' => false,],
            ['code' => 'ARS', 'name' => 'Argentine Peso', 'symbol' => '$', 'isDefault' => false,],
            ['code' => 'AUD', 'name' => 'Australian Dollar', 'symbol' => '$', 'isDefault' => false,],
            ['code' => 'AWG', 'name' => 'Aruban Guilder', 'symbol' => 'ƒ', 'isDefault' => false,],
            ['code' => 'AZN', 'name' => 'Azerbaijanian Manat', 'symbol' => 'ман', 'isDefault' => false,],
            ['code' => 'BAM', 'name' => 'Convertible Marks', 'symbol' => 'KM', 'isDefault' => false,],
            ['code' => 'BDT', 'name' => 'Bangladeshi Taka', 'symbol' => '৳', 'isDefault' => false,],
            ['code' => 'BBD', 'name' => 'Barbados Dollar', 'symbol' => '$', 'isDefault' => false,],
            ['code' => 'BGN', 'name' => 'Bulgarian Lev', 'symbol' => 'лв', 'isDefault' => false,],
            ['code' => 'BMD', 'name' => 'Bermudian Dollar', 'symbol' => '$', 'isDefault' => false,],
            ['code' => 'BND', 'name' => 'Brunei Dollar', 'symbol' => '$', 'isDefault' => false,],
            ['code' => 'BOB', 'name' => 'BOV Boliviano Mvdol', 'symbol' => '$b', 'isDefault' => false,],
            ['code' => 'BRL', 'name' => 'Brazilian Real', 'symbol' => 'R$', 'isDefault' => false,],
            ['code' => 'BSD', 'name' => 'Bahamian Dollar', 'symbol' => '$', 'isDefault' => false,],
            ['code' => 'BWP', 'name' => 'Pula', 'symbol' => 'P', 'isDefault' => false,],
            ['code' => 'BYR', 'name' => 'Belarussian Ruble', 'symbol' => '₽', 'isDefault' => false,],
            ['code' => 'BZD', 'name' => 'Belize Dollar', 'symbol' => 'BZ$', 'isDefault' => false,],
            ['code' => 'CAD', 'name' => 'Canadian Dollar', 'symbol' => '$', 'isDefault' => false,],
            ['code' => 'CHF', 'name' => 'Swiss Franc', 'symbol' => 'CHF', 'isDefault' => false,],
            ['code' => 'CLP', 'name' => 'CLF Chilean Peso Unidades de fomento', 'symbol' => '$', 'isDefault' => false,],
            ['code' => 'CNY', 'name' => 'Yuan Renminbi', 'symbol' => '¥', 'isDefault' => false,],
            [
                'code' => 'COP', 'name' => 'COU Colombian Peso Unidad de Valor Real', 'symbol' => '$',
                'isDefault' => false,
            ],
            ['code' => 'CRC', 'name' => 'Costa Rican Colon', 'symbol' => '₡', 'isDefault' => false,],
            ['code' => 'CUP', 'name' => 'CUC Cuban Peso Peso Convertible', 'symbol' => '₱', 'isDefault' => false,],
            ['code' => 'CZK', 'name' => 'Czech Koruna', 'symbol' => 'Kč', 'isDefault' => false,],
            ['code' => 'DKK', 'name' => 'Danish Krone', 'symbol' => 'kr', 'isDefault' => false,],
            ['code' => 'DOP', 'name' => 'Dominican Peso', 'symbol' => 'RD$', 'isDefault' => false,],
            ['code' => 'EGP', 'name' => 'Egyptian Pound', 'symbol' => '£', 'isDefault' => false,],
            ['code' => 'EUR', 'name' => 'Euro', 'symbol' => '€', 'isDefault' => false,],
            ['code' => 'FJD', 'name' => 'Fiji Dollar', 'symbol' => '$', 'isDefault' => false,],
            ['code' => 'FKP', 'name' => 'Falkland Islands Pound', 'symbol' => '£', 'isDefault' => false,],
            ['code' => 'GBP', 'name' => 'Pound Sterling', 'symbol' => '£', 'isDefault' => false,],
            ['code' => 'GIP', 'name' => 'Gibraltar Pound', 'symbol' => '£', 'isDefault' => false,],
            ['code' => 'GTQ', 'name' => 'Quetzal', 'symbol' => 'Q', 'isDefault' => false,],
            ['code' => 'GYD', 'name' => 'Guyana Dollar', 'symbol' => '$', 'isDefault' => false,],
            ['code' => 'HKD', 'name' => 'Hong Kong Dollar', 'symbol' => '$', 'isDefault' => false,],
            ['code' => 'HNL', 'name' => 'Lempira', 'symbol' => 'L', 'isDefault' => false,],
            ['code' => 'HRK', 'name' => 'Croatian Kuna', 'symbol' => 'kn', 'isDefault' => false,],
            ['code' => 'HUF', 'name' => 'Forint', 'symbol' => 'Ft', 'isDefault' => false,],
            ['code' => 'IDR', 'name' => 'Rupiah', 'symbol' => 'Rp', 'isDefault' => false,],
            ['code' => 'ILS', 'name' => 'New Israeli Sheqel', 'symbol' => '₪', 'isDefault' => false,],
            ['code' => 'IRR', 'name' => 'Iranian Rial', 'symbol' => '﷼', 'isDefault' => false,],
            ['code' => 'ISK', 'name' => 'Iceland Krona', 'symbol' => 'kr', 'isDefault' => false,],
            ['code' => 'JMD', 'name' => 'Jamaican Dollar', 'symbol' => 'J$', 'isDefault' => false,],
            ['code' => 'JPY', 'name' => 'Yen', 'symbol' => '¥', 'isDefault' => false,],
            ['code' => 'KGS', 'name' => 'Som', 'symbol' => 'лв', 'isDefault' => false,],
            ['code' => 'KHR', 'name' => 'Riel', 'symbol' => '៛', 'isDefault' => false,],
            ['code' => 'KPW', 'name' => 'North Korean Won', 'symbol' => '₩', 'isDefault' => false,],
            ['code' => 'KRW', 'name' => 'Won', 'symbol' => '₩', 'isDefault' => false,],
            ['code' => 'KYD', 'name' => 'Cayman Islands Dollar', 'symbol' => '$', 'isDefault' => false,],
            ['code' => 'KZT', 'name' => 'Tenge', 'symbol' => 'лв', 'isDefault' => false,],
            ['code' => 'LAK', 'name' => 'Kip', 'symbol' => '₭', 'isDefault' => false,],
            ['code' => 'LBP', 'name' => 'Lebanese Pound', 'symbol' => '£', 'isDefault' => false,],
            ['code' => 'LKR', 'name' => 'Sri Lanka Rupee', 'symbol' => '₨', 'isDefault' => false,],
            ['code' => 'LRD', 'name' => 'Liberian Dollar', 'symbol' => '$', 'isDefault' => false,],
            ['code' => 'LTL', 'name' => 'Lithuanian Litas', 'symbol' => 'Lt', 'isDefault' => false,],
            ['code' => 'LVL', 'name' => 'Latvian Lats', 'symbol' => 'Ls', 'isDefault' => false,],
            ['code' => 'MKD', 'name' => 'Denar', 'symbol' => 'ден', 'isDefault' => false,],
            ['code' => 'MNT', 'name' => 'Tugrik', 'symbol' => '₮', 'isDefault' => false,],
            ['code' => 'MUR', 'name' => 'Mauritius Rupee', 'symbol' => '₨', 'isDefault' => false,],
            [
                'code' => 'MXN', 'name' => 'MXV Mexican Peso Mexican Unidad de Inversion (UDI]', 'symbol' => '$',
                'isDefault' => false,
            ],
            ['code' => 'MYR', 'name' => 'Malaysian Ringgit', 'symbol' => 'RM', 'isDefault' => false,],
            ['code' => 'MZN', 'name' => 'Metical', 'symbol' => 'MT', 'isDefault' => false,],
            ['code' => 'NGN', 'name' => 'Naira', 'symbol' => '₦', 'isDefault' => false,],
            ['code' => 'NIO', 'name' => 'Cordoba Oro', 'symbol' => 'C$', 'isDefault' => false,],
            ['code' => 'NOK', 'name' => 'Norwegian Krone', 'symbol' => 'kr', 'isDefault' => false,],
            ['code' => 'NPR', 'name' => 'Nepalese Rupee', 'symbol' => '₨', 'isDefault' => false,],
            ['code' => 'NZD', 'name' => 'New Zealand Dollar', 'symbol' => '$', 'isDefault' => false,],
            ['code' => 'OMR', 'name' => 'Rial Omani', 'symbol' => '﷼', 'isDefault' => false,],
            ['code' => 'PAB', 'name' => 'USD Balboa US Dollar', 'symbol' => 'B/.', 'isDefault' => false,],
            ['code' => 'PEN', 'name' => 'Nuevo Sol', 'symbol' => 'S/.', 'isDefault' => false,],
            ['code' => 'PHP', 'name' => 'Philippine Peso', 'symbol' => 'Php', 'isDefault' => false,],
            ['code' => 'PKR', 'name' => 'Pakistan Rupee', 'symbol' => '₨', 'isDefault' => false,],
            ['code' => 'PLN', 'name' => 'Zloty', 'symbol' => 'zł', 'isDefault' => false,],
            ['code' => 'PYG', 'name' => 'Guarani', 'symbol' => 'Gs', 'isDefault' => false,],
            ['code' => 'QAR', 'name' => 'Qatari Rial', 'symbol' => '﷼', 'isDefault' => false,],
            ['code' => 'RON', 'name' => 'New Leu', 'symbol' => 'lei', 'isDefault' => false,],
            ['code' => 'RSD', 'name' => 'Serbian Dinar', 'symbol' => 'Дин.', 'isDefault' => false,],
            ['code' => 'RUB', 'name' => 'Russian Ruble', 'symbol' => 'руб', 'isDefault' => false,],
            ['code' => 'SAR', 'name' => 'Saudi Riyal', 'symbol' => '﷼', 'isDefault' => false,],
            ['code' => 'SBD', 'name' => 'Solomon Islands Dollar', 'symbol' => '$', 'isDefault' => false,],
            ['code' => 'SCR', 'name' => 'Seychelles Rupee', 'symbol' => '₨', 'isDefault' => false,],
            ['code' => 'SEK', 'name' => 'Swedish Krona', 'symbol' => 'kr', 'isDefault' => false,],
            ['code' => 'SGD', 'name' => 'Singapore Dollar', 'symbol' => '$', 'isDefault' => false,],
            ['code' => 'SHP', 'name' => 'Saint Helena Pound', 'symbol' => '£', 'isDefault' => false,],
            ['code' => 'SOS', 'name' => 'Somali Shilling', 'symbol' => 'S', 'isDefault' => false,],
            ['code' => 'SRD', 'name' => 'Surinam Dollar', 'symbol' => '$', 'isDefault' => false,],
            ['code' => 'SVC', 'name' => 'USD El Salvador Colon US Dollar', 'symbol' => '$', 'isDefault' => false,],
            ['code' => 'SYP', 'name' => 'Syrian Pound', 'symbol' => '£', 'isDefault' => false,],
            ['code' => 'THB', 'name' => 'Baht', 'symbol' => '฿', 'isDefault' => false,],
            ['code' => 'TRY', 'name' => 'Turkish Lira', 'symbol' => 'TL', 'isDefault' => false,],
            ['code' => 'TTD', 'name' => 'Trinidad and Tobago Dollar', 'symbol' => 'TT$', 'isDefault' => false,],
            ['code' => 'TWD', 'name' => 'New Taiwan Dollar', 'symbol' => 'NT$', 'isDefault' => false,],
            ['code' => 'UAH', 'name' => 'Hryvnia', 'symbol' => '₴', 'isDefault' => false,],
            ['code' => 'USD', 'name' => 'US Dollar', 'symbol' => '$', 'isDefault' => false,],
            [
                'code' => 'UYU', 'name' => 'UYI Uruguay Peso en Unidades Indexadas', 'symbol' => '$U',
                'isDefault' => false,
            ],
            ['code' => 'UZS', 'name' => 'Uzbekistan Sum', 'symbol' => 'лв', 'isDefault' => false,],
            ['code' => 'VEF', 'name' => 'Bolivar Fuerte', 'symbol' => 'Bs', 'isDefault' => false,],
            ['code' => 'VND', 'name' => 'Dong', 'symbol' => '₫', 'isDefault' => false,],
            ['code' => 'XCD', 'name' => 'East Caribbean Dollar', 'symbol' => '$', 'isDefault' => false,],
            ['code' => 'YER', 'name' => 'Yemeni Rial', 'symbol' => '﷼', 'isDefault' => false,],
            ['code' => 'ZAR', 'name' => 'Rand', 'symbol' => 'R', 'isDefault' => false,],
        ]);
    }
}
